[build]
  base = "AOG Events"
  command = "npm run build"
  publish = ".next"
  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_ANZ_GATEWAY_URL,NEXT_PUBLIC_ANZ_MERCHANT_ID,NEXT_PUBLIC_APP_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
